# LiveJava Configuration File

# language: Plugin language (en = English, tr = Türkçe)
language: "en"

# web-ide-port: The port where the VS Code-like Web IDE will be broadcasted.
# If you are using a VPS/Dedicated Server, you can leave it as 8080. (Access via: http://vds-ip:8080)
# If you are using a host like Magmanode or Pterodactyl Panel,
# you must allocate a new port from the 'Network' tab on your host's panel and type it here.
# After you change it type "/livejava editor reload" to reload port
web-ide-port: 8080

# allowed-ips: Additional IP addresses allowed to access the Web IDE.
# The IP of the player who types '/livejava editor' in-game is automatically allowed.
# You can add extra static IPs here (e.g., your home static IP) to bypass the game command.
allowed-ips: []
